### PR TITLE
Fix building on macOS w/ progress bar changes

### LINKED ISSUE #32: Unable to build on macOS 13.0 Ventura
Attempting to use Homebrew to install, or manually build from source, results in this error:

```bash
🕙 15:24:37 jeffbyrnes in rsgain/build on  master
♠ cmake .. -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for module 'libavcodec'
--   Found libavcodec, version 59.37.100
-- Checking for module 'libavformat'
--   Found libavformat, version 59.27.100
-- Checking for module 'libswresample'
--   Found libswresample, version 4.7.100
-- Checking for module 'libavutil'
--   Found libavutil, version 57.28.100
-- Checking for module 'taglib>=1.12'
--   Found taglib, version 1.13
-- Checking for module 'libebur128>=1.2.4'
--   Found libebur128, version 1.2.6
-- Checking for module 'inih'
--   Found inih, version 56
-- Checking for module 'fmt'
--   Found fmt, version 9.1.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jeffbyrnes/dev/rsgain/build

🕙 15:24:47 jeffbyrnes in rsgain/build on  master [?]
♠ make
[ 16%] Building CXX object src/CMakeFiles/rsgain.dir/rsgain.cpp.o
In file included from /Users/jeffbyrnes/dev/rsgain/src/rsgain.cpp:54:
/Users/jeffbyrnes/dev/rsgain/src/output.hpp:90:24: error: field has incomplete type 'struct winsize'
        struct winsize ws;
                       ^
/Users/jeffbyrnes/dev/rsgain/src/output.hpp:90:16: note: forward declaration of 'winsize'
        struct winsize ws;
               ^
1 error generated.
make[2]: *** [src/CMakeFiles/rsgain.dir/rsgain.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rsgain.dir/all] Error 2
make: *** [all] Error 2
```

Opening `output.hpp` in Visual Studio Code triggers showing the same issue on that line.

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Fix issue potentially introduced in b779ace835

Fixes #32

### CODE REVIEW

**Comment by complexlogic** [comment]
While you're at it, can you change this line
https://github.com/complexlogic/rsgain/blob/0bf454a6550ffa0ede30b097ebb17b2da380e8f6/src/easymode.cpp#L459
to `#ifndef _WIN32`

The issue you found will affect the preset file search path also

**Comment by jeffbyrnes** [comment]
Still builds,installs, and runs successfully on my Intel Mac.

**Comment by complexlogic** [comment]
@jeffbyrnes Please change this to `#ifndef`
https://github.com/jeffbyrnes/rsgain/blob/fix-macos-builds/src/easymode.cpp#L459
In other words, if NOT windows do this. Since checking for Unix is apparently unreliable, we'll check if its NOT windows instead. Also, please revert the comment, since Windows search path is handled in another block

Thanks for your support.

**Comment by jeffbyrnes** [comment]
Whoops! Thanks :)

**Comment by jeffbyrnes** [comment]
Ok, there we go. Amended & force-pushed the correct change. As you can tell, I’m somewhat blindly following your instructions, being not at all familiar w/ C++.

**Comment by jeffbyrnes** [comment]
Hmmm, a new failure:

```bash
[ 83%] Building CXX object src/CMakeFiles/rsgain.dir/easymode.cpp.o
/Users/jeffbyrnes/dev/rsgain/src/easymode.cpp:444:10: warning: expression result unused [-Wunused-value]
    for (it; it != list.end(); ++it) {
         ^~
/Users/jeffbyrnes/dev/rsgain/src/easymode.cpp:469:31: error: use of undeclared identifier 'PRESETS_DIR'
            join_paths(path, {PRESETS_DIR, preset});
                              ^
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/rsgain.dir/easymode.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rsgain.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by complexlogic** [comment]
Change this to `#ifndef _WIN32` too
https://github.com/complexlogic/rsgain/blob/320dcd3c67f890dcdc1fafc7557329daa86a7005/config/config.h.in#L6

**Comment by jeffbyrnes** [comment]
Builds & works with that last change.
